# ==========================================
# APPLICATION
# ==========================================

spring.application.name=dental-clinic-system


# ==========================================
# SQL SERVER DATABASE
# ==========================================

spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=sunrise_dental_clinic;encrypt=true;trustServerCertificate=true;sendTimeAsDatetime=false}

spring.datasource.username=${DB_USERNAME}

spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false


# ==========================================
# JSP VIEW RESOLVER
# ==========================================

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp